### PR TITLE
Basic Next Steps

### PR DESCRIPTION
**Pull request by Myoldmopar**
* Added sample code for:
  * temperature monitoring
  * web server
  * basic screen operation
  * sd card handling
* Added some hardware links in docs
* Added setup.py file to be a "proper" Python Project

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@gibslee we'll chat later about this :+1:

**Comment by gsl4295** [comment]
This is awesome! This is a pull request, so I have to merge it right?

**Comment by Myoldmopar** [comment]
Yep, go to the Files Changed tab at the top, and look at what I've added.  You can click on individual files or lines and make comments if you wish.  Once you are satisfied, you can mark it approved with the button in the top right:

image

Or...if you see something wrong, you can also "Request Changes" with that same button.

Once the code changes are approved, you come back here and make sure all the tests pass, which they are:

image

Once those are both satisfied, that's good enough, you can click Merge.

**Comment by gsl4295** [comment]
Ok that worked I guess!

**Pull request merged**
